### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by VadimMukabenov** [VadimMukabenov/my-own-sqlite-clone#1]
- [ ] implement B+ Tree for tables (leaf nodes connected via doubly-linked list)
- [ ] implement B Tree for indexes
- [ ] implement clustered index (B+ Tree for Primary Key, ID)
- [ ] implement non-clustered indexes (B or B+ Tree for other columns in the table)
- [ ] table can be stored in a data structure called Heap
- [ ] implement range queries
- [ ] implement ACID (Transactions, Isolations)
